import { Product } from './types'

// Mock products based on CSV data for development
export const mockProducts: Product[] = [
  {
    id: 'MAM_001',
    name: 'MAMOI® Baby swing Light grey 3-in-1',
    description: 'Wooden door bouncer that adapts to child\'s age - functions as baby swing with safety belt (6 months+) preschool swing without front barrier and swing bench (up to 10 years). Made with natural wood and organic cotton.',
    category: 'first-steps',
    subcategory: 'baby-swings',
    price: 59.99,
    originalPrice: 59.99,
    currency: 'EUR',
    sku: 'H13SZ',
    ageMin: 6,
    ageMax: 120,
    materials: ['Natural wood', 'organic cotton', 'light grey', 'silicone filling', 'metal rings'],
    dimensions: {
      length: 34,
      width: 34,
      height: 30,
    },
    weight: 2.5,
    safetyCertifications: ['Made in EU', 'hypoallergenic materials', 'no chemicals'],
    assemblyRequired: true,
    careInstructions: 'Store in dry place avoid rain/snow exposure easy to clean fabric',
    images: [
      'https://mamoi.me/wp-content/uploads/2023/06/lifestyle_3w1-szara_2-1.jpg',
      'https://mamoi.me/wp-content/uploads/2023/06/H13SZ_04.jpg',
      'https://mamoi.me/wp-content/uploads/2023/06/H13_JSZ_03-1-1.jpg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 days',
    productUrl: 'https://mamoi.me/mamoi-baby-swing-3-in-1-light-grey-safety-belt-hook-rope/',
    specifications: {
      max_load: '25kg',
      conversion_stages: 3,
      rope_included: true,
      ceiling_hook_included: true,
      fabric_washable: true,
    },
  },
  {
    id: 'MAM_002',
    name: 'MAMOI® Baby Hammock Cradle Natural',
    description: 'Suspended baby cradle for newborns with gentle rocking motion. Made from natural beech wood and organic cotton for maximum comfort and safety.',
    category: 'first-steps',
    subcategory: 'baby-hammocks',
    price: 59.99,
    originalPrice: 59.99,
    currency: 'EUR',
    sku: 'BCN01',
    ageMin: 0,
    ageMax: 12,
    materials: ['Beech wood frame', 'organic cotton fabric', 'natural color'],
    dimensions: {
      length: 70,
      width: 40,
      height: 25,
    },
    weight: 1.5,
    safetyCertifications: ['EN 1130:2019', 'CE certified', 'Made in EU'],
    assemblyRequired: true,
    careInstructions: 'Machine washable fabric at 30°C air dry only',
    images: [
      '/images/placeholder-product.svg',
      '/images/placeholder-product.svg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 days',
    productUrl: 'https://mamoi.me/baby-hammock-cradle-natural/',
    specifications: {
      max_load: '15kg',
      age_range: '0-12 months',
      suspension_system: 'spring',
      fabric_removable: true,
    },
  },
  {
    id: 'MAM_007',
    name: 'MAMOI® Balance Board Natural Wood',
    description: 'Wooden wobble board for balance training and creative play. Multi-functional design for various activities.',
    category: 'brave-explorers',
    subcategory: 'balance-boards',
    price: 29.99,
    originalPrice: 35.99,
    currency: 'EUR',
    sku: 'BBN01',
    ageMin: 18,
    ageMax: 150,
    materials: ['Natural beech wood', 'lacquered finish'],
    dimensions: {
      length: 80,
      width: 30,
      height: 18,
    },
    weight: 2.2,
    safetyCertifications: ['EN 71', 'CE certified', 'FSC wood'],
    assemblyRequired: false,
    careInstructions: 'Wipe clean with damp cloth oil periodically',
    images: [
      '/images/placeholder-product.svg',
      '/images/placeholder-product.svg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 days',
    productUrl: 'https://mamoi.me/balance-board-natural-wood/',
    specifications: {
      max_load: '200kg',
      curve_angle: '35 degrees',
      multi_use: true,
      felt_pads: true,
    },
  },
  {
    id: 'MAM_008',
    name: 'MAMOI® Balance Board with Cushion Pink',
    description: 'Balance board with removable cushion for added comfort and versatility. Perfect for yoga and balance exercises.',
    category: 'brave-explorers',
    subcategory: 'balance-boards',
    price: 76.99,
    originalPrice: 76.99,
    currency: 'EUR',
    sku: 'BBCP01',
    ageMin: 18,
    ageMax: 150,
    materials: ['Beech wood', 'pink cotton cushion', 'foam filling'],
    dimensions: {
      length: 80,
      width: 30,
      height: 18,
    },
    weight: 2.5,
    safetyCertifications: ['EN 71', 'CE certified', 'FSC wood'],
    assemblyRequired: false,
    careInstructions: 'Board: wipe clean Cushion: machine washable 40°C',
    images: [
      '/images/placeholder-product.svg',
      '/images/placeholder-product.svg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 days',
    productUrl: 'https://mamoi.me/balance-board-cushion-pink/',
    specifications: {
      max_load: '200kg',
      cushion_removable: true,
      yoga_compatible: true,
      anti_slip: true,
    },
  },
  {
    id: 'MAM_009',
    name: 'MAMOI® Pikler Triangle Small Natural',
    description: 'Classic Pikler climbing triangle for toddlers. Foldable design for easy storage with natural finish.',
    category: 'brave-explorers',
    subcategory: 'climbing-triangles',
    price: 49.99,
    originalPrice: 49.99,
    currency: 'EUR',
    sku: 'PTS01',
    ageMin: 12,
    ageMax: 72,
    materials: ['Pine wood', 'natural finish', 'metal hinges'],
    dimensions: {
      length: 80,
      width: 60,
      height: 70,
    },
    weight: 15,
    safetyCertifications: ['EN 71', 'CE certified', 'Pikler certified'],
    assemblyRequired: true,
    careInstructions: 'Wipe with damp cloth check screws monthly',
    images: [
      '/images/placeholder-product.svg',
      '/images/placeholder-product.svg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 days',
    productUrl: 'https://mamoi.me/pikler-triangle-small-natural/',
    specifications: {
      max_load: '50kg',
      foldable: true,
      bar_spacing: '12cm',
      wood_thickness: '2cm',
    },
  },
  {
    id: 'MAM_010',
    name: 'MAMOI® Pikler Triangle with Slide Combo',
    description: 'Pikler triangle with reversible slide/climbing ramp. Complete set for versatile climbing activities.',
    category: 'brave-explorers',
    subcategory: 'climbing-triangles',
    price: 139.99,
    originalPrice: 159.99,
    currency: 'EUR',
    sku: 'PTSC01',
    ageMin: 18,
    ageMax: 96,
    materials: ['Pine wood', 'plywood slide', 'natural finish'],
    dimensions: {
      length: 80,
      width: 60,
      height: 70,
    },
    weight: 28,
    safetyCertifications: ['EN 71', 'CE certified', 'Pikler certified'],
    assemblyRequired: true,
    careInstructions: 'Regular maintenance required assembly 45 min',
    images: [
      '/images/placeholder-product.svg',
      '/images/placeholder-product.svg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 days',
    productUrl: 'https://mamoi.me/pikler-triangle-slide-combo/',
    specifications: {
      max_load: '60kg',
      slide_reversible: true,
      includes: 'triangle and slide',
      angle_adjustable: true,
    },
  },
  {
    id: 'MAM_012',
    name: 'MAMOI® Learning Tower Natural',
    description: 'Kitchen helper tower for independent exploration. Adjustable platform height with safety rails.',
    category: 'brave-explorers',
    subcategory: 'learning-towers',
    price: 89.99,
    originalPrice: 89.99,
    currency: 'EUR',
    sku: 'LTN01',
    ageMin: 18,
    ageMax: 72,
    materials: ['Pine wood', 'natural finish', 'plywood platform'],
    dimensions: {
      length: 40,
      width: 40,
      height: 90,
    },
    weight: 20,
    safetyCertifications: ['EN 14988', 'CE certified'],
    assemblyRequired: true,
    careInstructions: 'Assembly required 30 min regular cleaning',
    images: [
      '/images/placeholder-product.svg',
      '/images/placeholder-product.svg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 days',
    productUrl: 'https://mamoi.me/learning-tower-natural/',
    specifications: {
      max_load: '50kg',
      platform_adjustable: true,
      safety_rail: true,
      anti_tip: true,
    },
  },
  {
    id: 'MAM_017',
    name: 'MAMOI® Swedish Ladder Natural Wood',
    description: 'Traditional wall bars for gymnastics and strength training. Multiple exercise possibilities.',
    category: 'confident-climbers',
    subcategory: 'swedish-ladders',
    price: 179.99,
    originalPrice: 179.99,
    currency: 'EUR',
    sku: 'SLN01',
    ageMin: 36,
    ageMax: 999,
    materials: ['Beech wood bars', 'pine frame', 'natural finish'],
    dimensions: {
      length: 80,
      width: 220,
      height: 30,
    },
    weight: 38,
    safetyCertifications: ['EN 1176', 'DIN 7910 certified'],
    assemblyRequired: true,
    careInstructions: 'Wall mounting required professional recommended',
    images: [
      '/images/placeholder-product.svg',
      '/images/placeholder-product.svg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 days',
    productUrl: 'https://mamoi.me/swedish-ladder-natural-wood/',
    specifications: {
      max_load: '130kg',
      bar_count: 14,
      wall_mount: true,
      pull_up_bar: true,
    },
  },
  {
    id: 'MAM_023',
    name: 'MAMOI® Children\'s Table and Chairs Set',
    description: 'Montessori-style furniture set with table and 2 chairs. Perfect height for independent activities.',
    category: 'creative-spaces',
    subcategory: 'furniture',
    price: 139.99,
    originalPrice: 139.99,
    currency: 'EUR',
    sku: 'CTCS01',
    ageMin: 18,
    ageMax: 84,
    materials: ['Pine wood', 'natural finish', 'child-safe edges'],
    dimensions: {
      length: 60,
      width: 40,
      height: 50,
    },
    weight: 25,
    safetyCertifications: ['EN 14988', 'children\'s furniture standard'],
    assemblyRequired: true,
    careInstructions: 'Assembly required 45 minutes',
    images: [
      '/images/placeholder-product.svg',
      '/images/placeholder-product.svg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 days',
    productUrl: 'https://mamoi.me/childrens-table-chairs-set/',
    specifications: {
      table_size: '60x40cm',
      chair_count: 2,
      height_adjustable: false,
      rounded_edges: true,
    },
  },
  {
    id: 'MAM_028',
    name: 'MAMOI® Teepee Play Tent Natural',
    description: 'Canvas teepee for imaginative play. Includes floor mat and window.',
    category: 'creative-spaces',
    subcategory: 'tents',
    price: 89.99,
    originalPrice: 89.99,
    currency: 'EUR',
    sku: 'TPTN01',
    ageMin: 24,
    ageMax: 120,
    materials: ['Cotton canvas', 'pine poles', 'cotton mat'],
    dimensions: {
      length: 160,
      width: 120,
      height: 180,
    },
    weight: 18,
    safetyCertifications: ['EN 71', 'CE certified', 'flame retardant'],
    assemblyRequired: true,
    careInstructions: 'Machine washable fabric assembly 15 min',
    images: [
      '/images/placeholder-product.svg',
      '/images/placeholder-product.svg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 days',
    productUrl: 'https://mamoi.me/teepee-play-tent-natural/',
    specifications: {
      height: '180cm',
      base: '120x120cm',
      window: true,
      floor_mat_included: true,
    },
  },
]

// Helper functions
export async function getMockProducts(): Promise<Product[]> {
  return mockProducts
}

export async function getMockProductById(id: string): Promise<Product | null> {
  return mockProducts.find(product => product.id === id) || null
}

export async function getFeaturedProducts(limit: number = 3): Promise<Product[]> {
  return mockProducts.slice(0, limit)
}

export async function getProductsByCategory(category: string): Promise<Product[]> {
  return mockProducts.filter(product => product.category === category)
}

export async function searchProducts(query: string): Promise<Product[]> {
  const lowerQuery = query.toLowerCase()
  return mockProducts.filter(product => 
    product.name.toLowerCase().includes(lowerQuery) ||
    product.description.toLowerCase().includes(lowerQuery) ||
    product.category.toLowerCase().includes(lowerQuery)
  )
}