import { Product } from './types'

// Complete product catalog imported from CSV - Marketing focused
export const allProducts: Product[] = [
  // === FIRST STEPS (0-18 months) ===
  {
    id: 'MAM_001',
    name: 'MAMOI® Baby swing Light grey 3-in-1',
    description: 'Roste s vaším dieťaťom! Drevená hojdačka sa prispôsobuje veku - od 6 mesiacov ako bezpečná hojdačka s pásikmi, neskôr bez bariér a nakoniec ako lavička (do 10 rokov). Vyrobená z prírodného dreva a organickej bavlny.',
    category: 'first-steps',
    subcategory: 'baby-swings',
    price: 59.99,
    originalPrice: 59.99,
    currency: 'EUR',
    sku: 'H13SZ',
    ageMin: 6,
    ageMax: 120,
    materials: ['Prírodné drevo', 'Organická bavlna', 'Kovové krúžky', 'Silicónová výplň'],
    dimensions: { length: 34, width: 34, height: 30 },
    weight: 2.5,
    safetyCertifications: ['Made in EU', 'Hypoalergénne materiály', 'Bez chemikálií'],
    assemblyRequired: true,
    careInstructions: 'Skladujte na suchom mieste, látku je možné prať',
    images: [
      'https://mamoi.me/wp-content/uploads/2023/06/lifestyle_3w1-szara_2-1.jpg',
      'https://mamoi.me/wp-content/uploads/2023/06/H13SZ_04.jpg',
      'https://mamoi.me/wp-content/uploads/2023/06/H13_JSZ_03-1-1.jpg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 dni',
    productUrl: 'https://mamoi.me/mamoi-baby-swing-3-in-1-light-grey-safety-belt-hook-rope/',
    specifications: {
      max_load: '25kg',
      conversion_stages: 3,
      rope_included: true,
      ceiling_hook_included: true,
      fabric_washable: true,
    },
    marketingHighlights: ['3v1 funkcionalita', 'Roste s dieťaťom', 'Prírodné materiály', 'Made in EU'],
    montessoriPrinciples: ['Nezávislosť', 'Motorický vývoj', 'Zmyslová stimulácia'],
  },

  {
    id: 'MAM_002',
    name: 'MAMOI® Baby Hammock Cradle Natural',
    description: 'Závesná kolíska pre novorodencov s jemným hojdacím pohybom. Vyrobená z prírodného bukového dreva a organickej bavlny pre maximálne pohodlie a bezpečnosť.',
    category: 'first-steps',
    subcategory: 'baby-hammocks',
    price: 59.99,
    originalPrice: 59.99,
    currency: 'EUR',
    sku: 'BCN01',
    ageMin: 0,
    ageMax: 12,
    materials: ['Bukové drevo', 'Organická bavlna', 'Prírodná farba'],
    dimensions: { length: 70, width: 40, height: 25 },
    weight: 1.5,
    safetyCertifications: ['EN 1130:2019', 'CE certifikát', 'Made in EU'],
    assemblyRequired: true,
    careInstructions: 'Látka sa môže prať v práčke na 30°C, sušiť na vzduchu',
    images: [
      'https://mamoi.me/baby-hammock-natural-1.jpg',
      'https://mamoi.me/baby-hammock-natural-2.jpg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 dni',
    productUrl: 'https://mamoi.me/baby-hammock-cradle-natural/',
    specifications: {
      max_load: '15kg',
      age_range: '0-12 mesiacov',
      suspension_system: 'pružinový',
      fabric_removable: true,
    },
    marketingHighlights: ['Jemné hojdanie', 'Pre novorodencov', 'Prírodné materiály', 'Odstrániteľná látka'],
    montessoriPrinciples: ['Pokojné prostredie', 'Prirodzený pohyb', 'Bezpečnosť'],
  },

  {
    id: 'MAM_003',
    name: 'MAMOI® Baby Gymnastics Mat Pink',
    description: 'Mäkká hracia podložka pre podlahové aktivity a bezpečnosť. Protišmyková spodná strana a práčka látka so senzorickými prvkami.',
    category: 'first-steps',
    subcategory: 'baby-mats',
    price: 49.99,
    originalPrice: 49.99,
    currency: 'EUR',
    sku: 'BGMP01',
    ageMin: 0,
    ageMax: 36,
    materials: ['Bavlnený poťah', 'Polyesterová výplň', 'Protišmyková guma'],
    dimensions: { length: 120, width: 80, height: 4 },
    weight: 1.2,
    safetyCertifications: ['EN 71 certifikát', 'Oeko-Tex Standard 100'],
    assemblyRequired: false,
    careInstructions: 'Poťah sa môže prať v práčke na 40°C, sušiť na nízkej teplote',
    images: [
      'https://mamoi.me/baby-gym-mat-pink-1.jpg',
      'https://mamoi.me/baby-gym-mat-pink-2.jpg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 dni',
    productUrl: 'https://mamoi.me/baby-gymnastics-mat-pink/',
    specifications: {
      thickness: '4cm',
      foldable: true,
      water_resistant: true,
      sensory_elements: true,
    },
    marketingHighlights: ['Senzorické prvky', 'Skladacia', 'Vodoodpudivá', 'Bezpečná hracia plocha'],
    montessoriPrinciples: ['Sloboda pohybu', 'Senzorická stimulácia', 'Samostatná hra'],
  },

  // === BRAVE EXPLORERS (18 months - 3 years) ===
  {
    id: 'MAM_007',
    name: 'MAMOI® Balance Board Natural Wood',
    description: 'Drevená balančná doska pre tréning rovnováhy a kreatívnu hru. Multifunkčný dizajn pre rôzne aktivity.',
    category: 'brave-explorers',
    subcategory: 'balance-boards',
    price: 29.99,
    originalPrice: 29.99,
    currency: 'EUR',
    sku: 'BBN01',
    ageMin: 18,
    ageMax: 150,
    materials: ['Prírodné bukové drevo', 'Lakovaný povrch'],
    dimensions: { length: 80, width: 30, height: 18 },
    weight: 2.2,
    safetyCertifications: ['EN 71', 'CE certifikát', 'FSC drevo'],
    assemblyRequired: false,
    careInstructions: 'Utrite vlhkou handrou, olejujte pravidelne',
    images: [
      'https://mamoi.me/balance-board-natural-1.jpg',
      'https://mamoi.me/balance-board-natural-2.jpg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 dni',
    productUrl: 'https://mamoi.me/balance-board-natural-wood/',
    specifications: {
      max_load: '200kg',
      curve_angle: '35 stupňov',
      multi_use: true,
      felt_pads: true,
    },
    marketingHighlights: ['Nosnosť 200kg', 'Multifunkčná', 'FSC certifikované drevo', 'Plstené podložky'],
    montessoriPrinciples: ['Rovnováha', 'Hrubá motorika', 'Kreatívna hra'],
  },

  {
    id: 'MAM_009',
    name: 'MAMOI® Pikler Triangle Small Natural',
    description: 'Klasický Pikler lezecký trojuholník pre batoliata. Skladací dizajn pre jednoduché skladovanie s prírodnou povrchovou úpravou.',
    category: 'brave-explorers',
    subcategory: 'climbing-triangles',
    price: 49.99,
    originalPrice: 49.99,
    currency: 'EUR',
    sku: 'PTS01',
    ageMin: 12,
    ageMax: 72,
    materials: ['Borovicové drevo', 'Prírodná povrchová úprava', 'Kovové pánty'],
    dimensions: { length: 80, width: 60, height: 70 },
    weight: 15,
    safetyCertifications: ['EN 71', 'CE certifikát', 'Pikler certifikát'],
    assemblyRequired: true,
    careInstructions: 'Utrite vlhkou handrou, kontrolujte skrutky mesačne',
    images: [
      'https://mamoi.me/pikler-triangle-small-1.jpg',
      'https://mamoi.me/pikler-triangle-small-2.jpg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 dni',
    productUrl: 'https://mamoi.me/pikler-triangle-small-natural/',
    specifications: {
      max_load: '50kg',
      foldable: true,
      bar_spacing: '12cm',
      wood_thickness: '2cm',
    },
    marketingHighlights: ['Skladací', 'Pikler certifikát', 'Bezpečné rozostupy', 'Prírodné drevo'],
    montessoriPrinciples: ['Lezenie', 'Hrubá motorika', 'Sebavedomie', 'Fyzický rozvoj'],
  },

  {
    id: 'MAM_012',
    name: 'MAMOI® Learning Tower Natural',
    description: 'Kuchynská pomocná veža pre nezávislé objavovanie. Nastaviteľná výška platformy s bezpečnostnými zábranami.',
    category: 'brave-explorers',
    subcategory: 'learning-towers',
    price: 89.99,
    originalPrice: 89.99,
    currency: 'EUR',
    sku: 'LTN01',
    ageMin: 18,
    ageMax: 72,
    materials: ['Borovicové drevo', 'Preglejková platforma', 'Prírodná povrchová úprava'],
    dimensions: { length: 40, width: 40, height: 90 },
    weight: 20,
    safetyCertifications: ['EN 14988', 'CE certifikát'],
    assemblyRequired: true,
    careInstructions: 'Montáž 30 min, pravidelné čistenie',
    images: [
      'https://mamoi.me/learning-tower-natural-1.jpg',
      'https://mamoi.me/learning-tower-natural-2.jpg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 dni',
    productUrl: 'https://mamoi.me/learning-tower-natural/',
    specifications: {
      max_load: '50kg',
      platform_adjustable: true,
      safety_rail: true,
      anti_tip: true,
    },
    marketingHighlights: ['Nastaviteľná výška', 'Bezpečnostné zábradlie', 'Anti-tip dizajn', 'Kuchynský pomocník'],
    montessoriPrinciples: ['Nezávislosť', 'Praktický život', 'Sebavedomie', 'Zapojenie do činností'],
  },

  // === CONFIDENT CLIMBERS (3-6 years) ===
  {
    id: 'MAM_016',
    name: 'MAMOI® Climbing Wall with 20 Holds',
    description: 'Nástenný lezecký systém s farebnými chytmi. Profesionálna kvalita pre domáce použitie.',
    category: 'confident-climbers',
    subcategory: 'climbing-walls',
    price: 224.99,
    originalPrice: 224.99,
    currency: 'EUR',
    sku: 'CW20H01',
    ageMin: 36,
    ageMax: 150,
    materials: ['Preglejková podložka', '20 plastových chytov', 'Montážny materiál'],
    dimensions: { length: 200, width: 100, height: 18 },
    weight: 45,
    safetyCertifications: ['EN 12572', 'Štandard lezeckej steny'],
    assemblyRequired: true,
    careInstructions: 'Vyžaduje sa profesionálna inštalácia',
    images: [
      'https://mamoi.me/climbing-wall-20-1.jpg',
      'https://mamoi.me/climbing-wall-20-2.jpg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 dni',
    productUrl: 'https://mamoi.me/climbing-wall-20-holds/',
    specifications: {
      hold_count: 20,
      difficulty_levels: 3,
      expandable: true,
      wall_mount: true,
    },
    marketingHighlights: ['20 chytov', '3 úrovne obťažnosti', 'Rozšíriteľná', 'Profesionálna kvalita'],
    montessoriPrinciples: ['Fyzická výzva', 'Sebavedomie', 'Riešenie problémov', 'Perzistencia'],
  },

  {
    id: 'MAM_017',
    name: 'MAMOI® Swedish Ladder Natural Wood',
    description: 'Tradičné rebriny pre gymnastiku a posilňovanie. Viacero možností cvičenia.',
    category: 'confident-climbers',
    subcategory: 'swedish-ladders',
    price: 179.99,
    originalPrice: 179.99,
    currency: 'EUR',
    sku: 'SLN01',
    ageMin: 36,
    ageMax: 999,
    materials: ['Bukové drevo', 'Borovicový rám', 'Prírodná povrchová úprava'],
    dimensions: { length: 80, width: 220, height: 30 },
    weight: 38,
    safetyCertifications: ['EN 1176', 'DIN 7910 certifikát'],
    assemblyRequired: true,
    careInstructions: 'Vyžaduje sa montáž na stenu, odporúčame profesionála',
    images: [
      'https://mamoi.me/swedish-ladder-natural-1.jpg',
      'https://mamoi.me/swedish-ladder-natural-2.jpg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 dni',
    productUrl: 'https://mamoi.me/swedish-ladder-natural-wood/',
    specifications: {
      max_load: '130kg',
      bar_count: 14,
      wall_mount: true,
      pull_up_bar: true,
    },
    marketingHighlights: ['Nosnosť 130kg', '14 priečok', 'Hrazda na zhyby', 'Tradičné rebriny'],
    montessoriPrinciples: ['Sila a vytrvalosť', 'Koordinácia', 'Disciplína', 'Fyzický rozvoj'],
  },

  {
    id: 'MAM_018',
    name: 'MAMOI® Complete Climbing Set Deluxe',
    description: 'Viacprvková lezecká súprava s trojuholníkom, šmýkačkou a príslušenstvom. Prémiová súprava pre aktívnu hru.',
    category: 'confident-climbers',
    subcategory: 'complete-sets',
    price: 259.99,
    originalPrice: 259.99,
    currency: 'EUR',
    sku: 'CCSD01',
    ageMin: 24,
    ageMax: 120,
    materials: ['Borovicové drevo', 'Preglejka', 'Kovový materiál', 'Prírodná povrchová úprava'],
    dimensions: { length: 'Rôzne', width: 'Rôzne', height: 180 },
    weight: 65,
    safetyCertifications: ['EN 71', 'EN 1176 certifikát'],
    assemblyRequired: true,
    careInstructions: 'Montáž 3-4 hodiny, podrobné inštrukcie',
    images: [
      'https://mamoi.me/climbing-set-deluxe-1.jpg',
      'https://mamoi.me/climbing-set-deluxe-2.jpg',
    ],
    stockStatus: 'In Stock',
    shippingCost: 4.99,
    shippingTime: '4 dni',
    productUrl: 'https://mamoi.me/complete-climbing-set-deluxe/',
    specifications: {
      components: 'trojuholník, šmýkačka, rebrík, hojdačka',
      max_load: '120kg',
      modular: true,
      indoor_outdoor: true,
    },
    marketingHighlights: ['Komplexná súprava', 'Modulárny systém', 'Vnútorné/vonkajšie', 'Nosnosť 120kg'],
    montessoriPrinciples: ['Komplexné výzvy', 'Progresívny vývoj', 'Kreativita', 'Fyzická kondícia'],
  },
];

// Export for use in components
export default allProducts;